Fixed qgroups options. Needs type=list.
```
Traceback (most recent call last):
File "/home/user/debug_dir/ansible_module_btrfs_subvolume.py", line 195, in <module>
main()
File "/home/user/debug_dir/ansible_module_btrfs_subvolume.py", line 119, in main
qgroups=' -i '.join(['']+module.params['qgroups']),
TypeError: can only concatenate list (not "str") to list
```

* Used `ansible/modules/core/files/find.py` as template.
* Use more sensible qgroups example. qgroup 1 is automatically mapped to
  `0/6`. Use `1/100` which are intended for system qgroups.
  See [quota support](https://btrfs.wiki.kernel.org/index.php/Quota_support)